[project]
name = "qwen-asr-x"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.135.2",
    "fireredvad>=0.0.2",
    "huggingface-hub>=0.36.2",
    "numpy>=2.2.6",
    "openai>=1.0.0",
    "python-dotenv>=1.0.0",
    "silero-vad>=6.2.1",
    "uvicorn>=0.42.0",
]

[project.optional-dependencies]
qwen = [
    "qwen-asr[vllm]>=0.0.6",
]
whisper = [
    "vllm",
]
cohere = [
    "transformers>=4.57.6",
]
# firered = [
#    "fireredasr2s @ git+https://github.com/FireRedTeam/FireRedASR2S.git",
# ]
diarize = [
    "pyannote-audio>=4.0.4",
]
all = [
    "qwen-asr-x[qwen,whisper,cohere,diarize]",
]
